id: A504EF5E4
title: Prayer for the Spread of the Tradition of Sera Khandro
type: translation
pechas:
- I21D4D51F
- ID6848740
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:47:07.529674
  last_modified_at: 2023-01-04 11:47:07.529685
  collections:
  - Dudjom Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  I21D4D51F/DF41: 1B57
  ID6848740/D888: 1B57
